package software2;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import software2.Tickets;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.*;

/**
/**
 *
 * @author omnia
 */
public class Flights extends javax.swing.JFrame {

    /**
     * Creates new form Flights
     */
    Connection con;
    public Flights() {
        initComponents();
        
         try {
               con = DriverManager.getConnection("jdbc:derby://localhost:1527/Flight","omnia","1234");
               
         } 
             catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        FlightCompaney = new javax.swing.JComboBox<>();
        Source = new javax.swing.JComboBox<>();
        Distination = new javax.swing.JComboBox<>();
        TakeOffDate = new javax.swing.JTextField();
        NumberOfSeats = new javax.swing.JTextField();
        TypeOfClass = new javax.swing.JComboBox<>();
        SaveButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        PassengerID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Flight Companey");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Source");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 70, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Distination");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        jLabel4.setBackground(new java.awt.Color(204, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Take Off Date");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 116, 160, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Number Of Seats");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Type Of Class");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, -1, -1));

        FlightCompaney.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Qatar Airways", "Egypt Air", "Air Arabia", "Air Cairo", "BadrAirline", "Fly Nas", "Iraqi Airways", "Delta Air Lines", "British Airways", "Turkish Airlines", "Singapore Airlines", "United Airlines" }));
        getContentPane().add(FlightCompaney, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, -1));

        Source.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua ", "Argentina", "Armenia", "Australia", "Benin ", "Bolivia", "Bosnia ", "Botswana", "Brazil", "Brunei", "Brunswick ", "Bulgaria", "Cabo Verde", "Cambodia", "Cameroon", "Canada", "Chad", "Chile", "China", "Colombia", "Comoros", "Congo ", "Costa Rica", "Cote ", "Croatia", "Cuba", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia", "Fiji", "Finland", "France", "Georgia", "Germany", "Ghana", "Grand ", "Greece", "Grenada", "Guatemala", "Guinea", "Holy See", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Italy", "Jamaica", "Japan", "Jordan", "Kiribati", "Korea", "Kosovo", "Kuwait", "Kyrgyzstan", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Nauru", "Nepal", "Netherlands", "Nicaragua", "Niger", "Nigeria", "Peru", "Philippines", "Piedmont-Sardinia*", "Poland", "Portugal", "Qatar", "Romania", "Russia", "Rwanda", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden", "Switzerland", "Syria", "Uganda", "Ukraine", "Yemen", "Zambia", "Zimbabwe" }));
        getContentPane().add(Source, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 130, -1));

        Distination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua ", "Argentina", "Armenia", "Australia", "Benin ", "Bolivia", "Bosnia ", "Botswana", "Brazil", "Brunei", "Brunswick ", "Bulgaria", "Cabo Verde", "Cambodia", "Cameroon", "Canada", "Chad", "Chile", "China", "Colombia", "Comoros", "Congo ", "Costa Rica", "Cote ", "Croatia", "Cuba", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia", "Fiji", "Finland", "France", "Georgia", "Germany", "Ghana", "Grand ", "Greece", "Grenada", "Guatemala", "Guinea", "Holy See", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Italy", "Jamaica", "Japan", "Jordan", "Kiribati", "Korea", "Kosovo", "Kuwait", "Kyrgyzstan", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Nauru", "Nepal", "Netherlands", "Nicaragua", "Niger", "Nigeria", "Peru", "Philippines", "Piedmont-Sardinia*", "Poland", "Portugal", "Qatar", "Romania", "Russia", "Rwanda", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden", "Switzerland", "Syria", "Uganda", "Ukraine", "Yemen", "Zambia", "Zimbabwe" }));
        getContentPane().add(Distination, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 130, -1));

        TakeOffDate.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(TakeOffDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 110, -1));

        NumberOfSeats.setBackground(new java.awt.Color(204, 204, 204));
        NumberOfSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberOfSeatsActionPerformed(evt);
            }
        });
        getContentPane().add(NumberOfSeats, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 110, -1));

        TypeOfClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "First Class ", "Business Class", "Economy Class" }));
        getContentPane().add(TypeOfClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, -1, -1));

        SaveButton.setText("Save");
        SaveButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SaveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, 200, 50));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Passenger ID");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        PassengerID.setText("Enter your ID");
        getContentPane().add(PassengerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 130, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Flights");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 210, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/software2/0.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        int num = 0;
        try
        {
            PreparedStatement stmt =con.prepareStatement ("insert into FLIGHT (FLIGHTCODE , FLIGHTCOMPANY ,SOURCE ,DISTINATION , TAKEOFFDATE, NUMBEROFSEATS , TYPEOFCLASS) values (?,?,?,?,?,?,?)");

            // PassengerID();
            stmt.setString(1, PassengerID.getText());
            stmt.setString(2, FlightCompaney.getSelectedItem().toString());
            stmt.setString(3, Source.getSelectedItem().toString());

            stmt.setString(4, Distination.getSelectedItem().toString());
            stmt.setString(5, TakeOffDate.getText());
            num = Integer.parseInt( NumberOfSeats.getText());
            if(num > 4)
            { JOptionPane.showMessageDialog(this,"Number Of Seats Can not be more Than 4");
              NumberOfSeats.setText("4");
                 stmt.setString(6, "4"); }
            else{
            stmt.setString(6,  String.valueOf(num));}

            stmt.setString(7,  TypeOfClass.getSelectedItem().toString());
            JOptionPane.showMessageDialog(this,"Flight Reserved");
            stmt.executeUpdate();

            this.setVisible(false);
            Tickets ticket =new Tickets(  );
            ticket.setVisible(true);

        }
        catch(SQLException ex)
        {
            //JOptionPane.showMessageDialog(this,ex);

        }
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void NumberOfSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberOfSeatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumberOfSeatsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Flights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Flights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Flights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Flights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Flights().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Distination;
    private javax.swing.JComboBox<String> FlightCompaney;
    private javax.swing.JTextField NumberOfSeats;
    private javax.swing.JTextField PassengerID;
    private javax.swing.JButton SaveButton;
    private javax.swing.JComboBox<String> Source;
    private javax.swing.JTextField TakeOffDate;
    private javax.swing.JComboBox<String> TypeOfClass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
