/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package software2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;

import java.sql.SQLException;
import javax.swing.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;


/*|| (nation.getSelectedItem()== null)*/

public class SignUp extends javax.swing.JFrame {
    
   
    public boolean IsRight( ){
        return (fname.equals("")|| lname.equals("")|| email.equals("")||pass.equals("")|| add.equals("")||pspo.equals("") || gender.isEmpty());
    }
 public static boolean ValiedEmail(String Email)
        {
            char[] arr=new char[Email.length()];
            if(Email.endsWith("@gmail.com"))
            {
                arr = Email.toCharArray();
                if (Character.isLetter(arr[0]))
                {
                    int count =Email.indexOf("@");
                    String temp = Email.substring(0, count);
                    if (temp.length()<12)
                    {
                        System.out.println("Email is True");
                        return true;
                    }
                    
                    else return false;
                   
                }
                else return false;
            }
            else return
                    false;
        }
 
 

public static boolean Pass(String password)
        {
            char[] x;
            int ch1=0,ch2=0,ch3=0;
            if ((password.length()==10))
            {
                x = password.toCharArray();
                for(int i=0;i<x.length;i++)
                {
                    if(Character.isLowerCase(x[i]))
                    {
                        ch1=1;
                    }
                }
                for(int i=0;i<x.length;i++)
                {
                    if (Character.isUpperCase(x[i]))
                    {
                        ch2=1;
                    }
                }
                for(int i=0;i<x.length;i++)
                {
                    if (Character.isDigit(x[i]))
                    {
                        ch3=1;
                    }
                }

                if (ch1==1&&ch2==1&&ch3==1)
                {
                    System.out.println("Pass is True");
                    return true;
                }
                  
            }
             System.out.println("Pass is wrong");
            return false;
        }

public boolean isInteger( String phone ) {
    try {
      Integer.parseInt( phone );
       System.out.println("true phone num");  
      return true;
        
    }
    catch( Exception e ) {
        
          JOptionPane.showMessageDialog(this, "Phone Number is wrong");
        
        this.setVisible(false);
         Opening open = new Opening ();
        open.setVisible(true);
    }
    return false;
}

   public boolean phone1 (String phone ){
       
       
       if (isInteger(phone)== true && phone.length()==11)
       {
           System.out.println("right phone num");
       return true;
       }
    else
          return false;

   }
   



   
  
        Connection con ;
       
    public SignUp() {
        
        
        initComponents();
        
        
                    try {
               con = DriverManager.getConnection("jdbc:derby://localhost:1527/Flight","omnia","1234");
            } 
             catch (SQLException ex) {
                ex.getMessage();
            }

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pspo = new javax.swing.JTextField();
        nation = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        add = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        pass = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        jLabel11.setText("jLabel11");

        jLabel12.setBackground(new java.awt.Color(204, 204, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setFocusable(false);
        jLabel12.setOpaque(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.SystemColor.activeCaption);
        setResizable(false);
        setSize(new java.awt.Dimension(1500, 1000));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("First Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 35, 80, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Last Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        fname.setName("fname"); // NOI18N
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 150, 40));

        lname.setName("lname"); // NOI18N
        getContentPane().add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 150, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Gender");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 83, 130, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Female");
        jRadioButton1.setName("gen"); // NOI18N
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Male");
        jRadioButton2.setName("gen"); // NOI18N
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Other");
        jRadioButton3.setName("gen"); // NOI18N
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setText("E-mail");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 110, -1));

        email.setName("email"); // NOI18N
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 185, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setText("Phone Number");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 180, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 102));
        jLabel6.setText("Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 140, -1));

        phone.setName("phone"); // NOI18N
        getContentPane().add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 150, 50));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 102));
        jLabel7.setText("Nationality");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 150, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 102));
        jLabel8.setText("Passport Number");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));

        pspo.setName("pasp"); // NOI18N
        getContentPane().add(pspo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 150, 40));

        nation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Afghan", " Andorran", "Antillean", " Argentinian ", "Australian", " Austrian", "Belgian", "Bolivian", "Brazilian", "Bulgarian ", " Burman ", "Cambodian", "Cameroun", "Ceylonese", "Chilean", "Chinese", "Colombian", "Congolese", "Costa Rican", "Croatian", "Cuban", "Cypriot", "Czech", "Danish", "Dominican", "Ecuadorians", "Egyptian", "Salvadorian", "English", "Ethiopian", "Finnish", "French", "Gabonese", "Gambian", "German", "Ghanaian", "British", "Greek", "Guatemalan", "Guinean", "Haitian", "Dutch", "Honduran", "Hungarian", "Icelander", "Indian", "Iranian", " Iraki", "Irish", "Yemani", "Italian", "Jamaican", " ", " " }));
        nation.setSelectedIndex(-1);
        nation.setName("nation"); // NOI18N
        nation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nationActionPerformed(evt);
            }
        });
        getContentPane().add(nation, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 102));
        jLabel10.setText("Address");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 70, 40));

        add.setColumns(20);
        add.setRows(5);
        add.setName("add"); // NOI18N
        jScrollPane1.setViewportView(add);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 310, 90));

        jButton1.setText("Sign Up");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, 170, 50));

        pass.setName("pass"); // NOI18N
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 150, 50));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 102));
        jLabel14.setText("Password should be 10 digits containing at least one Capital and Small letter ");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 560, 70));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 102));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 630));

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, 170, 50));

        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 440, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
         gender = "Female";       
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void nationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nationActionPerformed
     
     
               
    }//GEN-LAST:event_nationActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   try {   

                PreparedStatement stmt =con.prepareStatement ("insert into SIGNUP (PASSPORTNUM , LNAME ,PASSWORD ,FNAME , EMAIL, GENDER , PHONENUM ,NATIONALITY , ADDRESS ) values (?,?,?,?,?,?,?,?,?)");

                stmt.setString(1, pspo.getText());
                 stmt.setString(2, lname.getText());
                stmt.setString(3,String.valueOf(pass.getPassword()));
               
                stmt.setString(4, fname.getText());
                stmt.setString(5, email.getText());
                stmt.setString(6, gender);
         
                stmt.setString(7, phone.getText());
                stmt.setString(8, (String) nation.getSelectedItem());
              
                stmt.setString(9, add.getText());
                
                
                stmt.executeUpdate();
                
       
          if (IsRight()== false &&  Pass(pass.getText())== true &&ValiedEmail(email.getText())==true && phone1(phone.getText())== true ){
          JOptionPane.showMessageDialog(this, "Welcome"); 
             this.setVisible(false);
              Opening open =new Opening(); 
              open.setVisible(true);  
       }
               
                 
              
          

   }
               
   catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Something goes wrong");
                this.setVisible(false);
                Opening open = new Opening ();
                open.setVisible(true);
            }
  
         
                

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         pass.setText(null);
          fname.setText(null);
 lname.setText(null);    
        phone.setText(null);
           email.setText(null);
                add.setText(null);
                    pspo.setText(null);
                    
              
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        gender = "Other";
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
       gender = "Male";
    }//GEN-LAST:event_jRadioButton2ActionPerformed
   
       
    public static void main(String args[]) {
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea add;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lname;
    private javax.swing.JComboBox<String> nation;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField pspo;
    // End of variables declaration//GEN-END:variables
private String gender;
//private String nation; 

}


