package software2;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.*;

/**
/**
 *
 * @author omnia
 */
public class Tickets extends javax.swing.JFrame {

    /**
     * Creates new form Tickets
     */
    Connection con;
    public Tickets() {
        initComponents();
         try {
               con = DriverManager.getConnection("jdbc:derby://localhost:1527/Flight","omnia","1234");
               
         } 
             catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
      GetClass();
    }
 public int GetClass()
           
   {
       String query = "select * from FLIGHT";
       Connection con1 ;
       Statement st ;
        ResultSet rs;
        String flightClass = "";
        int cost = 0;
         try {
              con1 = DriverManager.getConnection("jdbc:derby://localhost:1527/Flight","omnia","1234");
              st = con1.createStatement();
              rs = st.executeQuery(query);
              
              while(rs.next())
              {flightClass = rs.getString("TYPEOFCLASS");}
              System.out.println(flightClass);
              if (flightClass == "First Class")
                    {cost = 4000;}
     
              else if (flightClass == "Business Class")
                     {cost= 3000;}
     
              else
                     {cost = 1000;}
              
              return cost;
                  
              
         } catch (SQLException ex) {
            ex.printStackTrace();
         }
         
        return cost;
   }
    
    public String GetNumberOfSeats()
           
   {
       String query = "select * from FLIGHT";
       Connection con1 ;
       Statement st ;
        ResultSet rs;
        String NSeats = "";
         try {
              con1 = DriverManager.getConnection("jdbc:derby://localhost:1527/Flight","omnia","1234");
              st = con1.createStatement();
              rs = st.executeQuery(query);
              
              while(rs.next())
              {NSeats = rs.getString("NUMBEROFSEATS");}
              System.out.println(NSeats);
              return NSeats;
                  
              
         } catch (SQLException ex) {
            ex.printStackTrace();
         }
         
        return NSeats;
   }
    
  
      public String TicketNumber()
    {
         String query = "select * from TICKETS";
       Connection con1 ;
       Statement st ;
        ResultSet rs;
        String ticketNum = "3";
        int num = 0;
         try {
              con1 = DriverManager.getConnection("jdbc:derby://localhost:1527/Flight","omnia","1234");
              st = con1.createStatement();
              rs = st.executeQuery(query);
              
              while(rs.next())
              {ticketNum = rs.getString("TICKETNUMBER");}
              num = Integer.parseInt(ticketNum);
              num++;
              System.out.println(ticketNum);
              ticketNum = String.valueOf(num);
              return ticketNum;
                  
              
         } catch (SQLException ex) {
            ex.printStackTrace();
         }
         
        return ticketNum;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PaymentMethod = new javax.swing.JComboBox<>();
        Price = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        TicketNumber = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ticket ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 110, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Payment Method");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 118, 26));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Price");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 118, 26));

        PaymentMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Check", "Credit Card", "Debit Card", "Bank Transfer", "Google Pay", " " }));
        PaymentMethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentMethodActionPerformed(evt);
            }
        });
        getContentPane().add(PaymentMethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 120, 26));

        Price.setBackground(new java.awt.Color(204, 204, 204));
        Price.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Price.setForeground(new java.awt.Color(255, 255, 255));
        Price.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 120, 26));

        jButton1.setText("Book");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 170, 54));

        TicketNumber.setBackground(new java.awt.Color(204, 204, 204));
        TicketNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TicketNumber.setForeground(new java.awt.Color(255, 255, 255));
        TicketNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(TicketNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 120, 26));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tickets");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/software2/AC.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PaymentMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentMethodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PaymentMethodActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {

            PreparedStatement stmt =con.prepareStatement ("insert into TICKETS (TICKETNUMBER, PRICE, PAYMENTMETHOD) values (?,?,?)");
            stmt.setString(1, TicketNumber());
            int price = (Integer.parseInt(GetNumberOfSeats()) * GetClass()  );
            Price.setText(String.valueOf(price));
            TicketNumber.setText(TicketNumber());
            stmt.setString(2, String.valueOf(price));
            stmt.setString(3, PaymentMethod.getSelectedItem().toString());
            stmt.executeUpdate();

              JOptionPane.showMessageDialog(null, "Tickets are Reserved");
             this.setVisible(false);
        Account account =new Account ();
        account.setVisible(true);
        } catch (SQLException ex) {
            //JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tickets().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> PaymentMethod;
    private javax.swing.JLabel Price;
    private javax.swing.JLabel TicketNumber;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
